#!/usr/bin/env bash

function create_dirs {
  set -e
  mkdir -p ${CACHE_DIR}/kernel-rpms
}

function download_kernel_sources {
  set -e
  echo "Downloading kernel source package..."
  pushd ${CACHE_DIR}/kernel-rpms
  if [ ! -f ${KERNEL_SRC_PKG} ]; then
    echo "Downloading: ${KERNEL_SRC_PKG}"
    if [ "$KRN_VENDOR" = "almalinux8" ]; then
      curl --fail -LO "${KERNEL_SRC_URL}"
    else
      curl --fail --no-progress-meter -LO "${KERNEL_SRC_URL}"
    fi
    if [ "$KRN_VENDOR" = "zefosa" ]; then
      echo "Downloading: ${KERNEL_TARBALL_URL}"
      curl --fail --no-progress-meter -LO "${KERNEL_TARBALL_URL}"
    fi
  fi
  popd
}

#!/bin/bash

# List of kernel config files
aarch64_config_files=(
    "kernel-aarch64-16k-debug-fedora.config"
    "kernel-aarch64-16k-fedora.config"
    "kernel-aarch64-64k-debug-rhel.config"
    "kernel-aarch64-64k-rhel.config"
    "kernel-aarch64-automotive-debug-rhel.config"
    "kernel-aarch64-automotive-rhel.config"
    "kernel-aarch64-debug-fedora.config"
    "kernel-aarch64-debug-rhel.config"
    "kernel-aarch64-fedora.config"
    "kernel-aarch64-rhel.config"
    "kernel-aarch64-rt-debug-fedora.config"
    "kernel-aarch64-rt-debug-rhel.config"
    "kernel-aarch64-rt-fedora.config"
    "kernel-aarch64-rt-rhel.config"
)

function prepare_kernel_sources {
  set -e
  echo "Initializing RPM build tree..."
  /usr/bin/rpmdev-setuptree
  rpm -Uvh "${CACHE_DIR}/kernel-rpms/${KERNEL_SRC_PKG}"
  echo "CONFIG_ZFS=y" >> "$(rpm --eval "%{_sourcedir}")/kernel-local"
  pushd "$(rpm --eval "%{_specdir}")"
  # error if there is no buildid pattern to replace
  grep "# define buildid .local" kernel.spec > /dev/null
  sed -i "s/# define buildid .local/%define buildid .zfs/" kernel.spec
  # Append changelog entry
  "${INPUT_DIR}/append-changelog.py" kernel.spec Zefosa zefosa@fogas.net "${KRN_VERSION}-${KRN_RELEASE}" "ZFS ${ZFS_PKG_VERSION} built-in (Giedrius M.)"
  if [ "$KRN_VENDOR" = "zefosa" ]; then
    pushd "$(rpm --eval "%{_sourcedir}")"
    # parameter added between 6.12.15 and 6.12.22
    config_param="CONFIG_MIPI_I3C_HCI_PCI=m"
    # Iterate through files and append the config parameter
    for file in "${aarch64_config_files[@]}"; do
        if [ -f "$file" ]; then
            echo "Adding $config_param to $file"
            echo "$config_param" >> "$file"
        else
            echo "Warning: File $file not found"
        fi
    done
    # Replace linux-6.12.15.tar.xz from src.rpm with latest linux-6.12.22.tar.xz
    rm -f "linux-${KRN_SRCRPM_VERSION}.tar.xz"
    mv "${CACHE_DIR}/kernel-rpms/${KERNEL_TARBALL}" .
    # rename to match final version number
    mv "kernel-abi-stablelists-${KRN_SRCRPM_VERSION}.tar.xz" "kernel-abi-stablelists-${KRN_VERSION}.tar.xz"
    mv "kernel-kabi-dw-${KRN_SRCRPM_VERSION}.tar.xz" "kernel-kabi-dw-${KRN_VERSION}.tar.xz"
    popd
    # back in SPEC dir now, patch correct version
    sed -i "s/%define specrpmversion ${KRN_SRCRPM_VERSION}/%define specrpmversion ${KRN_VERSION}/" kernel.spec
    sed -i "s/%define specversion ${KRN_SRCRPM_VERSION}/%define specversion ${KRN_VERSION}/" kernel.spec
    sed -i "s/%define tarfile_release ${KRN_SRCRPM_VERSION}/%define tarfile_release ${KRN_VERSION}/" kernel.spec
    sed -i "s/%define kabiversion ${KRN_SRCRPM_VERSION}/%define kabiversion ${KRN_VERSION}/" kernel.spec
  fi
  # extract + patch kernel sources
  /usr/bin/rpmbuild -bp kernel.spec
  popd

  if [ "$KRN_VENDOR" = "fedora" ] || [ "$KRN_VENDOR" = "zefosa" ]; then
    # ~/rpmbuild/BUILD/kernel-6.11.11/linux-6.11.11-200.zfs.fc40.x86_64/
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}"
    cp ./configs/kernel-${KRN_VERSION}-${KRN_ARCH}.config .config
    make prepare
    popd
  elif [ "$KRN_VENDOR" = "almalinux9" ]; then
    # build/BUILD/kernel-5.14.0-503.16.1.el9_5/linux-5.14.0-503.16.1.zfs.el9.x86_64
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}-${KRN_RELEASE}.el${OS_VERSION_MAJOR}_${OS_VERSION_MINOR}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}"
    cp ./configs/kernel-${KRN_VERSION}-${KRN_ARCH}.config .config
    make prepare
    popd
  fi

  if [ "$KRN_VENDOR" = "fedora" ] || [ "$KRN_VENDOR" = "zefosa" ]; then
    # ~/rpmbuild/BUILD/kernel-6.11.11
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}"
    cp -r "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}" "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}.orig"
    popd
  elif [ "$KRN_VENDOR" = "almalinux9" ]; then
    # build/BUILD/kernel-5.14.0-503.16.1.el9_5
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}-${KRN_RELEASE}.el${OS_VERSION_MAJOR}_${OS_VERSION_MINOR}"
    cp -r "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}" "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}.orig"
    popd
  fi
}

function prepare_zfs_sources {
  set -e
  pushd ${CACHE_DIR}
  if [ ! -d "${ZFS_GIT_TAG}" ]; then
    echo "Checking out ZFS sources..."
    if [ -z "${ZFS_GIT_CHERRY_PICK_COMMITS}" ]; then
      git clone --depth 1 --branch ${ZFS_GIT_TAG} ${ZFS_GITHUB_REPO} ${ZFS_GIT_TAG}
    else 
      git clone --branch ${ZFS_GIT_TAG} ${ZFS_GITHUB_REPO} ${ZFS_GIT_TAG}
    fi
  else
    echo "ZFS source tree already in place."
  fi
  popd

  pushd "${CACHE_DIR}/${ZFS_GIT_TAG}"
  if [ -n "${ZFS_GIT_CHERRY_PICK_COMMITS}" ]; then
    echo "Cherry-picking additional commits..."
    git config user.email "zefosator@build.system"
    git config user.name "Zefosator Build System"
    git stash || true
    for i in "${ZFS_GIT_CHERRY_PICK_COMMITS[@]}"
    do
      git cherry-pick "${i}"
    done
    git stash pop || true
  fi

  # easiest way to force ZFS use our version number for packages
  rm -rf "${CACHE_DIR}/${ZFS_GIT_TAG}/.git" || true

  if [ "${ENABLE_LICENSE_PATCH}" -eq 1 ]; then
    echo "Patching license..."
    sed -i "s/License:.*/License:       GPL v2/" META
  fi

  echo "Patching META version and release..."
  sed -i "s/Version:.*/Version:       ${ZFS_PKG_VERSION}/" META
  sed -i "s/Release:.*/Release:       ${ZFS_PKG_RELEASE}/" META

  echo "Patching META supported kernel version..."
  sed -i "s/Linux-Maximum:.*/Linux-Maximum: ${KRN_VERSION_MAJOR}.${KRN_VERSION_MINOR}/" META

  if [ ! -f "${ZFS_GIT_TAG}/Makefile" ]; then
    echo "Launching autogen..."
    sh autogen.sh
  fi

  echo "Configuring ZFS built-in build..."
  if [ "$KRN_VENDOR" = "fedora" ] || [ "$KRN_VENDOR" = "zefosa" ]; then
    ./configure --enable-linux-builtin --with-linux="$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}/"
    ./copy-builtin "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}/"
  elif [ "$KRN_VENDOR" = "almalinux9" ]; then
    ./configure --enable-linux-builtin --with-linux="$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}-${KRN_RELEASE}.el${OS_VERSION_MAJOR}_${OS_VERSION_MINOR}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}/"
    ./copy-builtin "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}-${KRN_RELEASE}.el${OS_VERSION_MAJOR}_${OS_VERSION_MINOR}/linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}/"
  fi
  popd
}

function build_zfs_rpms {
  set -e
  echo "Building ZFS RPM packages..."
  pushd "${CACHE_DIR}/${ZFS_GIT_TAG}"
  make -s -j8 rpm-utils
  popd
}

function move_zfs_rpms {
  set -e
  echo "Copying ZFS userspace packages to output dir..."
  pushd "${CACHE_DIR}/${ZFS_GIT_TAG}"
  for f in ./*.rpm; do 
    # filter for NON kmod-*.rpm
    if [[ ! "$f" =~ kmod-.*\.rpm ]]; then 
      cp -fv "$f" "${OUTPUT_DIR}/userspace/"
    fi
  done
  popd
}

function build_kernel_rpms {
  set -e
  echo "Preparing custom kernel patches..."
  cp "${INPUT_DIR}/patches/linker-discard-eh_frame.patch" "$(rpm --eval "%{_sourcedir}")/"
  cp "${INPUT_DIR}/patches/insn_decoder_test.patch" "$(rpm --eval "%{_sourcedir}")/"
  if [ "$KRN_VENDOR" = "fedora" ] || [ "$KRN_VENDOR" = "zefosa" ]; then
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}"
    diff -uNrp "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}.orig" \
      "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.fc${OS_VERSION_MAJOR}.${KRN_ARCH}" \
      > "$(rpm --eval "%{_sourcedir}")/openzfs.patch" || true
    popd
  elif [ "$KRN_VENDOR" = "almalinux9" ]; then
    pushd "$(rpm --eval "%{_builddir}")/kernel-${KRN_VERSION}-${KRN_RELEASE}.el${OS_VERSION_MAJOR}_${OS_VERSION_MINOR}"
    diff -uNrp "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}.orig" \
      "linux-${KRN_VERSION}-${KRN_RELEASE}.zfs.el${OS_VERSION_MAJOR}.${KRN_ARCH}" \
      > "$(rpm --eval "%{_sourcedir}")/openzfs.patch" || true
    popd
  fi
  pushd "$(rpm --eval "%{_specdir}")"
  echo "Patching kernel RPM spec..."
  sed -i '/Patch999999: linux-kernel-test.patch/a\Patch1113: insn_decoder_test.patch' kernel.spec
  sed -i '/ApplyOptionalPatch linux-kernel-test.patch/a\ApplyOptionalPatch insn_decoder_test.patch' kernel.spec
  sed -i '/Patch999999: linux-kernel-test.patch/a\Patch1112: openzfs.patch' kernel.spec
  sed -i '/ApplyOptionalPatch linux-kernel-test.patch/a\ApplyOptionalPatch openzfs.patch' kernel.spec
  sed -i '/Patch999999: linux-kernel-test.patch/a\Patch1111: linker-discard-eh_frame.patch' kernel.spec
  sed -i '/ApplyOptionalPatch linux-kernel-test.patch/a\ApplyOptionalPatch linker-discard-eh_frame.patch' kernel.spec
  # Add "Provides: zfs-kmod = 2.2.7\" below "Provides: kernel = %{specversion}-%{pkg_release}\"
  sed -i "/Provides: kernel = %{specversion}-%{pkg_release}/a\Provides: zfs-kmod = ${ZFS_PKG_VERSION}\\\\" kernel.spec
  echo "Building kernel packages..."
  rpmbuild -bb  --without configchecks --without headers --without cross-headers \
    --without kabichk --without doc --without selftests --with baseonly --without debuginfo \
    --without kernel-abi-stablelists \
    --target=${KRN_ARCH} kernel.spec
  popd
}

function move_kernel_rpms {
  set -e
  echo "Copying kernel packages to output dir..."
  pushd "$(rpm --eval "%{_rpmdir}")/${KRN_ARCH}"
  for f in ./*.rpm; do 
    cp -fv "$f" ${OUTPUT_DIR}/kernel/
  done
  popd
}

function cleanup_zfs {
  set -e
  echo "Cleaning ZFS build dir..."
  rm -rf "${CACHE_DIR}/${ZFS_GIT_TAG}"
}

function cleanup_kernel {
  set -e
  echo "Cleaning kernel RPM build tree..."
  rm -rf $(rpm --eval "%{_builddir}")/*
  rm -rf $(rpm --eval "%{_sourcedir}")/*
  rm -rf $(rpm --eval "%{_srcrpmdir}")/*
  rm -rf $(rpm --eval "%{_specdir}")/*
  find $(rpm --eval "%{_rpmdir}") -name "*.rpm" | xargs rm -f
}

function update_repo {
  set -e
  # clean and regenerate repository metadata
  mkdir -p ${REPO_DIR}/repodata
  rm -f ${REPO_DIR}/repodata/*
  createrepo ${REPO_DIR}
}
