#!/usr/bin/env bash

OS_VERSION_NUMBERS=($(echo "${OS_VERSION#[vV]}" | tr '.' '\n'))
OS_VERSION_MAJOR="${OS_VERSION_NUMBERS[0]}"
OS_VERSION_MINOR="${OS_VERSION_NUMBERS[1]}"

KRN_VERSION_NUMBERS=($(echo "${KRN_VERSION#[vV]}" | tr '.' '\n'))
KRN_VERSION_MAJOR="${KRN_VERSION_NUMBERS[0]}"
KRN_VERSION_MINOR="${KRN_VERSION_NUMBERS[1]}"
KRN_VERSION_PATCH="${KRN_VERSION_NUMBERS[2]}"

# default --krn-vendor
KRN_VENDOR=${KRN_VENDOR:=fedora}
# default --krn-arch
KRN_ARCH=${KRN_ARCH:=x86_64}

# additional list of commits to cherry-pick before building
if [ -n "${PARAMS}" ]; then
  ZFS_GIT_CHERRY_PICK_COMMITS="${PARAMS}"
fi
# Default Git URL for OpenZFS code checkout
ZFS_GITHUB_REPO=${ZFS_GITHUB_REPO:=https://github.com/openzfs/zfs.git}
# 1 = set license to GPL v2
ENABLE_LICENSE_PATCH=${ENABLE_LICENSE_PATCH:=0}
# 1 = drop BuildRequires line from RPM SPEC in case kernel-devel package has different name
ENABLE_SPEC_PATCH=${ENABLE_SPEC_PATCH:=0}
# docker/podman base image
BASE_IMAGE_NAME=${BASE_IMAGE_NAME:=fedora:${OS_VERSION_MAJOR}}
# podman/docker built image
IMAGE_NAME=${IMAGE_NAME:=zefosator-image-fedora${OS_VERSION_MAJOR}}
# default kernel package base name
KERNEL_PKG_BASE_NAME=${KERNEL_PKG_BASE_NAME:=kernel}
STANDARD_PACKAGES=""
# RPM packages required to build kernel RPMs from source RPM
STANDARD_PACKAGES+="asciidoc audit-libs-devel bindgen binutils-devel clang dracut dwarves "
STANDARD_PACKAGES+="elfutils-devel fuse-devel gcc-c++ gettext glibc-static hmaccalc java-devel "
STANDARD_PACKAGES+="kernel-rpm-macros libbabeltrace-devel libbpf-devel libcap-devel libcap-ng-devel "
STANDARD_PACKAGES+="libmnl-devel libnl3-devel libtraceevent-devel libtracefs-devel lld llvm-devel "
STANDARD_PACKAGES+="lvm2 ncurses-devel net-tools newt-devel nss-tools numactl-devel pciutils-devel "
STANDARD_PACKAGES+="perl-devel perl-generators pesign python3-docutils python3-pyyaml rust rust-src "
STANDARD_PACKAGES+="systemd-boot-unsigned systemd-ukify tpm2-tools xmlto xz-devel perl-ExtUtils-Embed "
STANDARD_PACKAGES+="wget rpmdevtools bc hostname python3-devel rsync "
# RPM packages required to build ZFS RPMs
STANDARD_PACKAGES+="gcc make autoconf automake libtool rpm-build kernel-rpm-macros "
STANDARD_PACKAGES+="libblkid-devel libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel "
STANDARD_PACKAGES+="libattr-devel elfutils-libelf-devel libffi-devel createrepo bison flex "
STANDARD_PACKAGES+="git-core "
# Extra RPM packages to install after standard packages are installed
EXTRA_PACKAGES="python3 python3-setuptools python3-cffi python3-packaging "

if [ "$KRN_VENDOR" = "fedora" ]; then
  # Build OpenZFS kmod for standard Fedora kernel  
  STANDARD_PACKAGES+="dkms libtirpc-devel rpmrebuild ncompress "
  KERNEL_PKG_BASE_NAME=kernel
  KERNEL_SRC_PKG=${KERNEL_PKG_BASE_NAME}-${KRN_VERSION}-${KRN_RELEASE}.fc${OS_VERSION_MAJOR}.src.rpm
  # https://kojipkgs.fedoraproject.org/packages/kernel/6.12.6/100.fc40/src/kernel-6.12.6-100.fc40.src.rpm
  KERNEL_SRC_URL="https://kojipkgs.fedoraproject.org/packages/kernel/${KRN_VERSION}/${KRN_RELEASE}.fc${OS_VERSION_MAJOR}/src/${KERNEL_SRC_PKG}"
fi
