#!/usr/bin/bash

# kokio dataseto snapshota padaryti pries diegima
SNAP_DATASET=gmp1/fedora/38
# podman image pavadinimas
IMAGE_NAME=zefosator-image-${RELEASEVER}
KERNEL_REPO_DIR=/home/giedriusm/Repo/zfs/${REPO_NAME}/kernel/x86_64
USERSPACE_REPO_DIR=/home/giedriusm/Repo/zfs/${REPO_NAME}/user/x86_64

STANDARD_PACKAGES="gcc make autoconf automake libtool rpm-build kernel-rpm-macros "
STANDARD_PACKAGES+="libblkid-devel libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel "
STANDARD_PACKAGES+="python3 python3-devel python3-setuptools python3-cffi python3-packaging "
STANDARD_PACKAGES+="libattr-devel elfutils-libelf-devel libffi-devel createrepo bison flex "

# paketai, kuriu diegimo tvarka skiriasi prieklausomai nuo distribucijos
if [ "$KRNVENDOR" = "fedora" ] || [ "$KRNVENDOR" = "kwizart" ]; then
  STANDARD_PACKAGES+="dkms libtirpc-devel rpmrebuild ncompress "
elif [ "$KRNVENDOR" = "almalinux" ]; then
  STANDARD_PACKAGES+="epel-release "
  EXTRA_PACKAGES="dkms libtirpc-devel rpmrebuild ncompress "
fi


