#!/usr/bin/env bash

export ZEFOSATOR_VERSION=2.0.0

set -e
source ./args_parser

if [ -n "${PARAMS_FILE}" ]; then
  source "${PARAMS_FILE}"
fi

if [ -n "${SHOW_VERSION}" ]; then
  show_version
elif [ -n "${DO_BUILD}" ] && \
    [ -n "${ZFS_GIT_TAG}" ] && [ -n "${ZFS_PKG_VERSION}" ] && [ -n "${ZFS_PKG_RELEASE}" ] && \
    [ -n "${KRN_VERSION}" ] && [ -n "${KRN_RELEASE}" ] && [ -n "${OS_VERSION}" ]; then
  if [ "$(id -u)" -eq 0 ]
    then echo "Please run as non-root"
    exit
  fi
  source ./config 
  source ./library
  create_variables_file
  build_image
  build_rpms_in_container
  #build_rpms_local
elif [ -n "${DO_INITRAMFS}" ] && \
    [ -n "${KRN_VERSION}" ] && [ -n "${KRN_RELEASE}" ] && [ -n "${OS_VERSION}" ]; then
  if [ "$(id -u)" -ne 0 ]
    then echo "Please run as root"
    exit
  fi
  source ./config
  source ./library
  update_initramfs
  list_initramfs_zfs
  list_installed_kernels
else
  show_help
fi
