
name: Build Fedora 41 packages for AMD64 arch

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch and specific params file
  push:
    branches: [ "main" ]
    paths:
      - 'params/fedora-41-x86_64.params'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PKG_ID: fedora41
  PARAMS_FILE: params/fedora-41-x86_64.params

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build ZFS built-in kernel and userspace packages
        run: ./zefosator --build --params-file $PARAMS_FILE

      - name: Upload selected userspace packages
        env:
          ARTIFACT_UPLOAD_KEY: ${{ secrets.ARTIFACT_UPLOAD_KEY }}
        run: |
          pushd ./output/userspace/
          rm -f *.src.rpm
          rm -f *debug*.rpm
          rm -f *test*.rpm
          rm -f *kmod*.rpm
          tar -cf "$PKG_ID-zfs-userspace-packages.tar" *.rpm
          sha256sum "$PKG_ID-zfs-userspace-packages.tar" > "$PKG_ID-zfs-userspace-packages.sha256"
          curl -u "$ARTIFACT_UPLOAD_KEY:" -T "$PKG_ID-zfs-userspace-packages.tar" "https://cloud.fogas.net/public.php/webdav/$PKG_ID-zfs-userspace-packages.tar"
          curl -u "$ARTIFACT_UPLOAD_KEY:" -T "$PKG_ID-zfs-userspace-packages.sha256" "https://cloud.fogas.net/public.php/webdav/$PKG_ID-zfs-userspace-packages.sha256"
          popd

      - name: Upload selected kernel packages
        env:
          ARTIFACT_UPLOAD_KEY: ${{ secrets.ARTIFACT_UPLOAD_KEY }}
        run: |
          pushd ./output/kernel/
          rm -f *uki-virt*.rpm
          tar -cf "$PKG_ID-zfs-kernel-packages.tar" *.rpm
          sha256sum "$PKG_ID-zfs-kernel-packages.tar" > "$PKG_ID-zfs-kernel-packages.sha256"
          curl -u "$ARTIFACT_UPLOAD_KEY:" -T "$PKG_ID-zfs-kernel-packages.tar" "https://cloud.fogas.net/public.php/webdav/$PKG_ID-zfs-kernel-packages.tar"
          curl -u "$ARTIFACT_UPLOAD_KEY:" -T "$PKG_ID-zfs-kernel-packages.sha256" "https://cloud.fogas.net/public.php/webdav/$PKG_ID-zfs-kernel-packages.sha256"
          popd
