# This is a basic workflow to help you get started with Actions

name: Build Fedora 40 Packages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build ZFS built-in kernel for Fedora 40
        run: ./zefosator --build --params-file params/fedora-40.params

      - name: Remove unnecessary userspace packages
        run: |
          rm -f output/userspace/*.src.rpm
          rm -f output/userspace/*debug*.rpm
          rm -f output/userspace/*test*.rpm
          rm -f output/userspace/*kmod*.rpm

      - name: Upload ZFS userspace packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora40-zfs-userspace-packages.zip
          path: output/userspace/
          compression-level: 0 # no compression

      - name: Remove unnecessary kernel packages
        run: |
          rm -f output/userspace/*uki-virt*.rpm

      - name: Upload ZFS kernel packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora40-zfs-kernel-packages.zip
          path: output/kernel/
          compression-level: 0 # no compression
